-- Insertar géneros literarios en la tabla generos
INSERT INTO generos (nombre) VALUES
-- Ficción
('Ficción'),
('Novela'),
('Ciencia Ficción'),
('Fantasía'),
('Terror'),
('Suspense'),
('Thriller'),
('Misterio'),
('Policiaco'),
('Romance'),
('Histórica'),
('Aventura'),
('Distopía'),
('Realismo Mágico'),
('Gótica'),
('Western'),

-- No Ficción
('No Ficción'),
('Biografía'),
('Autobiografía'),
('Ensayo'),
('Historia'),
('Ciencia'),
('Filosofía'),
('Psicología'),
('Autoayuda'),
('Desarrollo Personal'),
('Negocios'),
('Economía'),
('Política'),
('Divulgación Científica'),
('Viajes'),
('Cocina'),
('Arte'),
('Música'),
('Deportes'),
('Salud'),

-- Otros géneros
('Poesía'),
('Teatro'),
('Cómic'),
('Manga'),
('Novela Gráfica'),
('Infantil'),
('Juvenil'),
('Educativo'),
('Técnico'),
('Religión'),
('Espiritualidad'),
('Humor'),
('Crónica'),
('Periodismo'),
('Testimonio');